import { validateUnitContent } from "@/content/schema";

export const unit01 = validateUnitContent({
  id: "unit01",
  slug: "at-the-park",
  title: { en: "At the park", vi: "Ở công viên" },
  descriptionVi:
    "Học năm từ vựng về công viên và cách dùng tính từ so sánh hơn.",
  level: "A1",
  vocabulary: [
    {
      id: "unit01-swing",
      word: "swing",
      meaningVi: "xích đu",
      exampleEn: "The swing is red.",
      imageSrc: "/images/unit-01/swing.webp",
      imageAltVi: "Một chiếc xích đu màu đỏ trong công viên.",
      pronunciation: { kind: "tts", text: "swing", lang: "en-US" },
    },
    {
      id: "unit01-slide",
      word: "slide",
      meaningVi: "cầu trượt",
      exampleEn: "The slide is tall.",
      imageSrc: "/images/unit-01/slide.webp",
      imageAltVi: "Một chiếc cầu trượt cao trong công viên.",
      pronunciation: { kind: "tts", text: "slide", lang: "en-US" },
    },
    {
      id: "unit01-kite",
      word: "kite",
      meaningVi: "cái diều",
      exampleEn: "The kite is in the sky.",
      imageSrc: "/images/unit-01/kite.webp",
      imageAltVi: "Một chiếc diều nhiều màu đang bay trên trời.",
      pronunciation: { kind: "tts", text: "kite", lang: "en-US" },
    },
    {
      id: "unit01-bench",
      word: "bench",
      meaningVi: "ghế dài",
      exampleEn: "The bench is near the pond.",
      imageSrc: "/images/unit-01/bench.webp",
      imageAltVi: "Một chiếc ghế dài bằng gỗ trong công viên.",
      pronunciation: { kind: "tts", text: "bench", lang: "en-US" },
    },
    {
      id: "unit01-pond",
      word: "pond",
      meaningVi: "ao",
      exampleEn: "The pond has ducks.",
      imageSrc: "/images/unit-01/pond.webp",
      imageAltVi: "Một cái ao nhỏ có hai con vịt đang bơi.",
      pronunciation: { kind: "tts", text: "pond", lang: "en-US" },
    },
  ],
  grammar: {
    id: "unit01-comparatives",
    title: { en: "Comparative adjectives", vi: "Tính từ so sánh hơn" },
    explanationVi:
      "Dùng tính từ so sánh hơn để so sánh hai người, con vật hoặc đồ vật.",
    rule: "short adjective + -er + than",
    examplesEn: [
      "The slide is taller than the bench.",
      "The pond is bigger than the puddle.",
    ],
    practice: [
      {
        id: "gp-01",
        instructionVi: "Chọn từ đúng để hoàn thành câu.",
        sentenceEn: "The slide is ___ than the bench.",
        options: [
          { id: "gp-01-a", text: "tall" },
          { id: "gp-01-b", text: "taller" },
          { id: "gp-01-c", text: "tallest" },
        ],
        correctOptionId: "gp-01-b",
        explanationVi: "Câu so sánh hai vật dùng taller than.",
      },
      {
        id: "gp-02",
        instructionVi: "Chọn từ đúng để hoàn thành câu.",
        sentenceEn: "The pond is ___ than the puddle.",
        options: [
          { id: "gp-02-a", text: "big" },
          { id: "gp-02-b", text: "bigger" },
          { id: "gp-02-c", text: "biggest" },
        ],
        correctOptionId: "gp-02-b",
        explanationVi: "Big gấp đôi phụ âm cuối trước khi thêm -er: bigger.",
      },
      {
        id: "gp-03",
        instructionVi: "Chọn từ đúng để hoàn thành câu.",
        sentenceEn: "The bench is ___ than the swing seat.",
        options: [
          { id: "gp-03-a", text: "long" },
          { id: "gp-03-b", text: "longer" },
          { id: "gp-03-c", text: "longest" },
        ],
        correctOptionId: "gp-03-b",
        explanationVi: "Câu so sánh hai vật dùng longer than.",
      },
    ],
  },
  quizBank: [
    {
      id: "q-01",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "unit01-slide",
      word: "slide",
      options: [
        { id: "q-01-a", text: "cầu trượt" },
        { id: "q-01-b", text: "xích đu" },
        { id: "q-01-c", text: "ghế dài" },
      ],
      correctOptionId: "q-01-a",
      explanationVi: "Slide nghĩa là cầu trượt.",
    },
    {
      id: "q-02",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "unit01-swing",
      word: "swing",
      options: [
        { id: "q-02-a", text: "cái ao" },
        { id: "q-02-b", text: "xích đu" },
        { id: "q-02-c", text: "cái diều" },
      ],
      correctOptionId: "q-02-b",
      explanationVi: "Swing nghĩa là xích đu.",
    },
    {
      id: "q-03",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "unit01-bench",
      word: "bench",
      options: [
        { id: "q-03-a", text: "cầu trượt" },
        { id: "q-03-b", text: "cái ao" },
        { id: "q-03-c", text: "ghế dài" },
      ],
      correctOptionId: "q-03-c",
      explanationVi: "Bench nghĩa là ghế dài.",
    },
    {
      id: "q-04",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "unit01-pond",
      word: "pond",
      options: [
        { id: "q-04-a", text: "cái ao" },
        { id: "q-04-b", text: "cái diều" },
        { id: "q-04-c", text: "xích đu" },
      ],
      correctOptionId: "q-04-a",
      explanationVi: "Pond nghĩa là ao.",
    },
    {
      id: "q-05",
      type: "image-choice",
      instructionVi: "Nhìn hình và chọn từ tiếng Anh đúng.",
      imageSrc: "/images/unit-01/swing.webp",
      imageAltVi: "Một chiếc xích đu màu đỏ trong công viên.",
      options: [
        { id: "q-05-a", text: "swing" },
        { id: "q-05-b", text: "slide" },
        { id: "q-05-c", text: "bench" },
      ],
      correctOptionId: "q-05-a",
      explanationVi: "Xích đu trong tiếng Anh là swing.",
    },
    {
      id: "q-06",
      type: "image-choice",
      instructionVi: "Nhìn hình và chọn từ tiếng Anh đúng.",
      imageSrc: "/images/unit-01/kite.webp",
      imageAltVi: "Một chiếc diều nhiều màu đang bay trên trời.",
      options: [
        { id: "q-06-a", text: "pond" },
        { id: "q-06-b", text: "kite" },
        { id: "q-06-c", text: "slide" },
      ],
      correctOptionId: "q-06-b",
      explanationVi: "Cái diều trong tiếng Anh là kite.",
    },
    {
      id: "q-07",
      type: "image-choice",
      instructionVi: "Nhìn hình và chọn từ tiếng Anh đúng.",
      imageSrc: "/images/unit-01/pond.webp",
      imageAltVi: "Một cái ao nhỏ có hai con vịt đang bơi.",
      options: [
        { id: "q-07-a", text: "bench" },
        { id: "q-07-b", text: "swing" },
        { id: "q-07-c", text: "pond" },
      ],
      correctOptionId: "q-07-c",
      explanationVi: "Ao trong tiếng Anh là pond.",
    },
    {
      id: "q-08",
      type: "grammar-choice",
      instructionVi: "Chọn từ đúng để hoàn thành câu.",
      sentenceEn: "The slide is ___ than the bench.",
      options: [
        { id: "q-08-a", text: "tall" },
        { id: "q-08-b", text: "taller" },
        { id: "q-08-c", text: "tallest" },
      ],
      correctOptionId: "q-08-b",
      explanationVi: "Câu so sánh hai vật dùng taller than.",
    },
    {
      id: "q-09",
      type: "grammar-choice",
      instructionVi: "Chọn từ đúng để hoàn thành câu.",
      sentenceEn: "The pond is ___ than the puddle.",
      options: [
        { id: "q-09-a", text: "big" },
        { id: "q-09-b", text: "biggest" },
        { id: "q-09-c", text: "bigger" },
      ],
      correctOptionId: "q-09-c",
      explanationVi: "Big gấp đôi phụ âm cuối trước khi thêm -er: bigger.",
    },
    {
      id: "q-10",
      type: "grammar-choice",
      instructionVi: "Chọn từ đúng để hoàn thành câu.",
      sentenceEn: "The bench is ___ than the swing seat.",
      options: [
        { id: "q-10-a", text: "longer" },
        { id: "q-10-b", text: "long" },
        { id: "q-10-c", text: "longest" },
      ],
      correctOptionId: "q-10-a",
      explanationVi: "Câu so sánh hai vật dùng longer than.",
    },
  ],
  rewards: { vocabulary: 10, grammar: 10, quiz: 20 },
  quizRules: { questionsPerAttempt: 7, passPercent: 70 },
});
