import { validateUnitContent } from "@/content/schema";

export const unit00Fixture = validateUnitContent({
  id: "unit00",
  slug: "fixture-playground",
  title: { en: "Fixture Playground", vi: "Sân chơi dữ liệu giả" },
  descriptionVi: "Dữ liệu giả để kiểm tra engine trước khi ghép Unit 1 thật.",
  level: "A1",
  vocabulary: [
    ["ball", "ball", "quả bóng", "The ball is red."],
    ["tree", "tree", "cái cây", "The tree is tall."],
    ["kite", "kite", "cái diều", "The kite is in the sky."],
    ["bench", "bench", "ghế dài", "The bench is near the tree."],
    ["duck", "duck", "con vịt", "The duck is in the pond."],
  ].map(([id, word, meaningVi, exampleEn]) => ({
    id: `fixture-${id}`,
    word,
    meaningVi,
    exampleEn,
    imageSrc: `/images/fixture/${id}.webp`,
    imageAltVi: `Hình minh họa ${meaningVi}`,
    pronunciation: { kind: "tts" as const, text: word, lang: "en-US" as const },
  })),
  grammar: {
    id: "fixture-comparatives",
    title: { en: "Comparative adjectives", vi: "Tính từ so sánh hơn" },
    explanationVi: "Dùng dạng so sánh hơn khi so sánh hai người hoặc hai vật.",
    rule: "short adjective + -er + than",
    examplesEn: ["The tree is taller than the bench.", "The red ball is bigger than the blue ball."],
    practice: [
      ["gp-01", "The tree is ___ than the bench.", "taller", ["tall", "taller", "tallest"]],
      ["gp-02", "A ball is ___ than a marble.", "bigger", ["big", "bigger", "biggest"]],
      ["gp-03", "The duck is ___ than the tree.", "smaller", ["small", "smaller", "smallest"]],
    ].map(([id, sentenceEn, answer, words]) => ({
      id: id as string,
      instructionVi: "Chọn từ đúng để hoàn thành câu.",
      sentenceEn: sentenceEn as string,
      options: (words as string[]).map((text, index) => ({ id: `${id}-${index + 1}`, text })),
      correctOptionId: `${id}-${(words as string[]).indexOf(answer as string) + 1}`,
      explanationVi: "Câu so sánh hai sự vật nên dùng dạng tính từ so sánh hơn.",
    })),
  },
  quizBank: [
    {
      id: "q-01",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "fixture-ball",
      word: "ball",
      options: [{ id: "q-01-a", text: "quả bóng" }, { id: "q-01-b", text: "cái cây" }, { id: "q-01-c", text: "con vịt" }],
      correctOptionId: "q-01-a",
      explanationVi: "Ball nghĩa là quả bóng.",
    },
    {
      id: "q-02",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "fixture-tree",
      word: "tree",
      options: [{ id: "q-02-a", text: "cái diều" }, { id: "q-02-b", text: "cái cây" }, { id: "q-02-c", text: "ghế dài" }],
      correctOptionId: "q-02-b",
      explanationVi: "Tree nghĩa là cái cây.",
    },
    {
      id: "q-03",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "fixture-kite",
      word: "kite",
      options: [{ id: "q-03-a", text: "cái diều" }, { id: "q-03-b", text: "quả bóng" }, { id: "q-03-c", text: "con vịt" }],
      correctOptionId: "q-03-a",
      explanationVi: "Kite nghĩa là cái diều.",
    },
    {
      id: "q-04",
      type: "meaning-choice",
      instructionVi: "Chọn nghĩa đúng của từ.",
      wordId: "fixture-bench",
      word: "bench",
      options: [{ id: "q-04-a", text: "cái cây" }, { id: "q-04-b", text: "ghế dài" }, { id: "q-04-c", text: "cái diều" }],
      correctOptionId: "q-04-b",
      explanationVi: "Bench nghĩa là ghế dài.",
    },
    ...["ball", "kite", "duck"].map((word, index) => ({
      id: `q-0${index + 5}`,
      type: "image-choice" as const,
      instructionVi: "Nhìn hình và chọn từ tiếng Anh đúng.",
      imageSrc: `/images/fixture/${word}.webp`,
      imageAltVi: `Hình kiểm thử cho từ ${word}`,
      options: ["ball", "kite", "duck"].map((text, optionIndex) => ({ id: `q-0${index + 5}-${optionIndex + 1}`, text })),
      correctOptionId: `q-0${index + 5}-${index + 1}`,
      explanationVi: `Đây là hình minh họa cho từ ${word}.`,
    })),
    ...[
      ["q-08", "The tree is ___ than the bench.", "taller", ["tall", "taller", "tallest"]],
      ["q-09", "The ball is ___ than the marble.", "bigger", ["big", "bigger", "biggest"]],
      ["q-10", "The duck is ___ than the tree.", "smaller", ["small", "smaller", "smallest"]],
    ].map(([id, sentenceEn, answer, words]) => ({
      id: id as string,
      type: "grammar-choice" as const,
      instructionVi: "Chọn từ đúng để hoàn thành câu.",
      sentenceEn: sentenceEn as string,
      options: (words as string[]).map((text, index) => ({ id: `${id}-${index + 1}`, text })),
      correctOptionId: `${id}-${(words as string[]).indexOf(answer as string) + 1}`,
      explanationVi: "So sánh hai sự vật nên dùng tính từ so sánh hơn.",
    })),
  ],
  rewards: { vocabulary: 10, grammar: 10, quiz: 20 },
  quizRules: { questionsPerAttempt: 7, passPercent: 70 },
});
